# Generated by Django 3.1 on 2020-09-21 09:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('about_me', models.TextField()),
                ('experience', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('st_date', models.DateTimeField(default=datetime.datetime.now)),
                ('ed_date', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='technology',
            field=models.ManyToManyField(to='portfolio.Technology'),
        ),
    ]
