# Generated by Django 3.1 on 2020-08-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=None, default='', max_length=50)),
                ('lname', models.CharField(blank=None, default='', max_length=50)),
                ('username', models.CharField(blank=None, default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('zip_code', models.IntegerField()),
                ('tnc', models.BooleanField(default=False)),
            ],
        ),
    ]
