# Generated by Django 3.1 on 2020-08-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('', 'Choose'), ('MG', 'Minas Gerais'), ('SP', 'Sau paulo'), ('RJ', 'Rio De janerio')], max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('check_me_out', models.BooleanField(default=False)),
            ],
        ),
    ]
