# Generated by Django 3.1 on 2020-09-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_application'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_text'], name='polls_quest_questio_13fa43_idx'),
        ),
    ]
